"""empty message

Revision ID: 0de8ad6c8c1c
Revises: fb6020bf02ce
Create Date: 2024-09-05 15:17:50.816257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de8ad6c8c1c'
down_revision = 'fb6020bf02ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctorId', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('doctorId')

    # ### end Alembic commands ###
