"""empty message

Revision ID: 1ee25acc030b
Revises: b1eb09a9f210
Create Date: 2024-09-05 16:13:01.991999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee25acc030b'
down_revision = 'b1eb09a9f210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('appointment_doctorId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctor', ['doctorId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointment_doctorId_fkey', 'user', ['doctorId'], ['id'])

    # ### end Alembic commands ###
