"""empty message

Revision ID: 47307bf43cf9
Revises: c0705bcc02b2
Create Date: 2024-09-05 19:03:13.161079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47307bf43cf9'
down_revision = 'c0705bcc02b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###
